'*****************************************************
'***用于xshell软件收集NetApp Ontap Cmode日志 ** *
'*****************************************************
def Main():
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set admin;rows 0")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("metrocluster check run")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("node show -fields serialnumber,node,systemid,model,vendor,health")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver show -type admin")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("date")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system controller show -fields node,system-id,model,part-number,serial-number")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -fields data-protocol,address,role")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -fields data-protocol,address,role,home-node,home-port,wwpn")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -role node-mgmt -fields lif,status-admin,status-oper,address,home-node")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("cifs share show -fields vserver,share-name,cifs-server,path,file-umask,volume")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("cluster image show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("net int show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("sp show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network route show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("version")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("disk show -fields type,model,physical-size")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command sysconfig -a")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command sysconfig -ca")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("node show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("node show -fields uptime")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show -fields size,usedsize,percent-used,availsize,root,maxraidsize,diskcount,mirror,raidtype,node,storage-type,availsize,volcount,state")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show -root false -fields size,usedsize,percent-used,availsize")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show -instance")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggregate efficiency cross-volume-dedupe show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show -r")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show -s -fields disk,disk-type,disk-rpm,checksum-style,usable-size,total-size,is-disk-zeroed")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("aggr show-status -aggregate *")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage aggregate object-store config show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage aggregate object-store show-space")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage aggregate show -fields composite")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("broadcast-domain show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("cluster show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("cluster time-service ntp server show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set -c off;set d;cluster kernel-service config show;set admin")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("cifs share show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("df -g")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("df -i")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("disk show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("export-policy rule show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("igroup show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("igroup show -v")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("ifgrp show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("ifgrp show -instance")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("license show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("lun show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("lun show -fields ostype,vserver,size,state,mapped,size-used,serial-hex")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("lun show -v")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("lun show -fields vserver,volume,path,state,mapped,size,size-used,serial-hex,mapped,space-reserve,space-allocation,creation-timestamp,node,ostype")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("lun show -m")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("lun show -fields volume")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("sp network show -fields ip-address,netmask,gateway -address-family IPv4")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("net port show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network fcp adapter show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface failover-groups show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("net int show -instance")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -failover")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -fields data-protocol,address,role,home-node,home-port,wwpn")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -role cluster-mgmt -fields lif,status-admin,status-oper,address")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network interface show -role node-mgmt -fields lif,status-admin,status-oper,address")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("net port show -link up -fields node,port,ipspace,broadcast-domain,link,mtu,speed-admin,speed-oper,health-status")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network fcp adapter show -instance")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network fcp adapter show -fields sfp-rx-power,sfp-tx-power")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("network device-discovery show -instance")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * sasadmin expander_map")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * sasadmin shelf")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command disk show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command storage show disk -p")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command storage show fault -v")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command sysconfig -V")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command sysconfig -d")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command sysconfig -r")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * environment status")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command rdfile /etc/qual_devices_v3")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("snapmirror show -fields lag-time,total-progress,healthy,relationship-group-type,state,status,schedule")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("snapshot list")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("snapshot show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk show -fields power-on-hours,model,rpm,type,firmware-revision,serial-number,physical-size,usable-size")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk show -ssd-wear")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk show -fields grown-defect-list-count")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk error show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk show -broken")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage disk option show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage errors show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage failover show -fields node,partner-name,possible,state-description")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage shelf show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage path show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage port show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage port show -instance")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("controller memory dimm show -fields pds-id,slotname,uecc-count,cecc-count")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage shelf location-led show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage shelf show -port")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage shelf show -fields psu-op-status,fan-op-status,module-op-status, module-fw-revision,module-type,node")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("storage shelf show -fields shelf,serial-number,module-type,disk-count,module-fw-revision,product-id")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system environment sensors show -fields node,state,name -state !normal")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system chassis show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system chassis fru show -state !ok,!GOOD")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system health subsystem show -health !ok")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system health alert show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system controller fru show -fields node,fru-name,subsystem,status")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("system controller service-event show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("security certificate show -fields expiratio -type server")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("ucadmin show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -fields vserver,volume,volume-style-extended,aggr-list,aggregate,size,available,state,junction-path,junction-active,type,create-time,fractional-reserve,space-guarantee,files,files-used")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set -c off;set d;vol show -fields vserver,volume,volume-style-extended,aggr-list,aggregate,size,available,state,junction-path,junction-active,type,create-time,fractional-reserve,space-guarantee,files,files-used;set admin")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -fields junction-path,node,aggregate,state,junction-active")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -fields policy,junction-path,size,used,files,files-used,aggr-list,node,security-style")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set -c off;set d;cluster kernel-service config show -fields kcs-enable-takeover;set admin")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -fields percent-used")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -fields state")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -fields fractional-reserve,snapshot-policy")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vol show -is-constituent true")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver cifs share show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver cifs show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver export-policy rule show -fields clientmatch,policyname,ruleindex,protocol,rorule,rwrule,anon,superuser")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver fcp initiator show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver iscsi initiator show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver nfs show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver show -type data -fields allowed-protocols,admin-state,operational-state,type")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver iscsi show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver cifs show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver fcp show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver nfs show -fields v3,v4.0,v4.1")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver show-aggregates")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver show-protocols")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("vserver services name-service dns show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set -c off;set d;run -node * ha-config show;set admin")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set -c off;set d;system controller fru led show;set admin")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("metrocluster show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("metrocluster node show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("metrocluster vserver show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("cluster peer show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * storage show switch")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * storage show bridge")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("event log show -severity EMERGENCY")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("event log show -severity ALERT")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("event log show -severity WARNING")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("event log show -severity ERROR")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("statistics node show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("qos statistics latency show -iterations 5")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("qos statistics performance show -iterations 5")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("run -node * -command sysstat -suc 9")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("metrocluster check show")
                xsh.Screen.Send('\r')
                xsh.Screen.WaitForString("::>")
                xsh.Screen.Send("set admin")
                xsh.Screen.Send('\r')
